### PR TITLE
Updating to use Microsoft.Extensions.DependencyInjections.Specifications

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
@ipjohnson, thought I might help you out with https://github.com/ipjohnson/Grace/issues/28. The DI implementation abstraction is generally stable now and the plan is to let the abstractions bake.

We created a test specification as part of our RC2 milestone (RC1 is very close to real to NuGet) and I updated your previous fork to build against the DI abstractions and test against the test abstractions.

The changes work generally ok - although I'm not sure if there's a better way of doing implementation factories: https://github.com/ipjohnson/DependencyInjection/pull/1/files#diff-c257000cc479578f0b1ae50e8fca631aR47. 

The changes have two failing tests that I could some help with:

1. https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Specification.Tests/DependencyInjectionSpecificationTests.cs#L210

The implementation factory doesn't do scoping correctly and creates new instances all the time. My guess is I've not set it up correctly.

2.https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Specification.Tests/DependencyInjectionSpecificationTests.cs#L529

Seems like this shouldn't be part of the test specification - it's a container behavior that we shouldn't need to test. I'll move this out.

**Comment by ipjohnson** [comment]
Hi Pravan,

I'll pull in your merge tonight or later this week (sometimes week nights don't work out the way you want) and see about getting the scoping test passing. Hopefully it's not a bug in Grace but if so I'll put together a fix and do a release for Grace. 

Thanks a bunch this makes things much easier.

-Ian

**Comment by ipjohnson** [comment]
Hi Pravan,

I merged in your changes and tried to build the project and I'm getting this odd error. 

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets(159,5): error : The design time host build failed with the following error: preprocessorSymbols

I tried updating my build tool version to beta8 but that didn't seem to solve the problem (caused others).

I've been a little removed from the VS2015 changes so I imagine it's something I haven't done to setup my environment. Any ideas?

Thanks
-Ian

**Comment by pranavkm** [comment]
cc @troydai \ @davidfowl. Any idea what's going on here?

**Comment by davidfowl** [comment]
Did this ever get resolved?

**Comment by ipjohnson** [comment]
Hi David, 

I actually didn't hear back from anyone so it kind of fell off my radar. I can update my 2015 env and give it a try again this evening. 

-Ian

**Comment by ipjohnson** [comment]
Hi david and pranavkm,

Sorry to bother you but I've been trying to get this going and I'm having significant trouble getting it working. I know it's my environment as I have trouble compiling some of the other DI container projects.

I know you guys are knee deep in RC 2.0, so I'm wondering if I should try getting this going or wait till RC 2.0 is released?

Thanks
-Ian

**Comment by pranavkm** [comment]
The src part of it should be relatively easy conversion to rc2 \ netstandard. I'd perhaps wait for a bit until new tooling is out. I'd be happy to resend the PR with the right set of changes for RC2 once things are in place

**Comment by ipjohnson** [comment]
Very cool, I'm actually really excited to see RC2 as I liked what you guys were doing with the Beta.

Thanks
-Ian

**Comment by ipjohnson** [comment]
Hi Pranavkm,

I've got my environment up and going and I was able to get this repository working. I believe I've got everything correct but I was wondering if you'd take a quick look when you have a moment.

I think I'm going to move the code to a different repository soon as it's not really a fork any more.

Thanks
-Ian

**Comment by pranavkm** [comment]
cc @halter73

**Comment by pranavkm** [comment]
I can send changes to update this to use `dotnet.exe` instead of DNX. Let me know once you update it and I can send a PR there

**Comment by ipjohnson** [comment]
Ok I've checked everything into the new repository at 
https://github.com/ipjohnson/Grace.DependencyInjection.Extensions

**Comment by pranavkm** [comment]
Ahh, for some reason I thought you were still using DNX to build. The repo looks like it's in pretty good shape. We should have RTM builds on our nightly feeds this week and on nuget.org in a couple weeks, so you should be able to produce RTM versions of packages pretty soon.

**Comment by ipjohnson** [comment]
Sounds great, thanks for all the help. 

By the way really TagHelper + DI + nuget the possibilities are endless. Hopefully people see the power in delivering custom controls with built in intellisense and create tons of packages (bootstrap control that contains label, typed editor and validation in one markup <editor for="prop"/> would save so much time and energy).

You guys are rolling out some really great software.

**Comment by pranavkm** [comment]
Also, if you have packages available for this - feel free to send a PR to add a link to https://github.com/aspnet/DependencyInjection/#using-other-containers-with-microsoftextensionsdependencyinjection

**Pull request merged**
